02 样本内网格搜索（只看 IS：2012-08 ~ 2019-12）
止损 {6,8,10,12%,无} × 止盈 {15,25,40%,无} × {追踪,固定}。**此处不看样本外。**

In [1]:
%run 00_engine.ipynb

数据区间: 2011-10-03 ~ 2026-10-07 | 信号分布: {'TQQQ': 2904, 'TECL': 249, 'TECS': 203, 'BSV': 150, 'UVXY': 133, 'SPXL': 17}

In [2]:
runs=run_all()
rows=[{'trail':c[0],'sl':c[1],'tp':c[2],**metrics(runs[c][0],a=IS_START,b=IS_END)} for c in combos]
g=pd.DataFrame(rows)
for trailing in [True,False]:
    sub=g[g.trail==trailing]
    print('== 追踪止损' if trailing else '== 固定止损','（行=止损，列=止盈）')
    for col in ['Sharpe','MDD']:
        print('IS',col); display(sub.pivot(index='sl',columns='tp',values=col).round(2))

== 追踪止损 （行=止损，列=止盈）
IS Sharpe

tp    NaN   0.15  0.25  0.40
sl
NaN   0.99  0.99  1.08  1.04
0.06  0.71  0.72  0.78  0.80
0.08  0.56  0.62  0.64  0.65
0.10  0.55  0.63  0.64  0.64
0.12  0.65  0.78  0.75  0.73

IS MDD

tp    NaN   0.15  0.25  0.40
sl
NaN  -0.74 -0.64 -0.63 -0.74
0.06 -0.49 -0.42 -0.46 -0.49
0.08 -0.56 -0.50 -0.54 -0.56
0.10 -0.59 -0.53 -0.58 -0.59
0.12 -0.64 -0.57 -0.62 -0.64

== 固定止损 （行=止损，列=止盈）
IS Sharpe

tp    NaN   0.15  0.25  0.40
sl
0.06  0.76  0.82  0.94  0.83
0.08  0.62  0.66  0.78  0.69
0.10  0.76  0.85  0.93  0.82
0.12  0.80  0.85  0.94  0.86

IS MDD

tp    NaN   0.15  0.25  0.40
sl
0.06 -0.69 -0.53 -0.52 -0.69
0.08 -0.75 -0.65 -0.61 -0.75
0.10 -0.73 -0.58 -0.57 -0.73
0.12 -0.73 -0.62 -0.61 -0.73